# Generated by Django 5.2.6 on 2025-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cart", "0002_category_parent_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
