version: '3.8'
services:
db:
image: postgres:15
environment:
POSTGRES_DB: usersdb
POSTGRES_USER: postgres
POSTGRES_PASSWORD: password
ports:
- '5432:5432'
volumes:
- pgdata:/var/lib/postgresql/data


fastapi:
build: .
command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
- ./app:/app/app
- ./alembic:/app/alembic
- ./alembic.ini:/app/alembic.ini
environment:
- DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/usersdb
- JWT_SECRET=supersecretreplace_me
- JWT_ALGORITHM=HS256
- ACCESS_TOKEN_EXPIRE_MINUTES=1440
ports:
- '8001:8000'
depends_on:
- db


volumes:
pgdata: