"""ass hashed_password field to model

Revision ID: 643a1555a94b
Revises: 180852f6db59
Create Date: 2025-09-10 07:55:10.761258

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "643a1555a94b"
down_revision: Union[str, Sequence[str], None] = "180852f6db59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column(
#         "users",
#         sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     )
#     # ### end Alembic commands ###


def upgrade():
    # اضافه کردن ستون hashed_password به صورت nullable اول
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=True))

    # پر کردن ستون با مقدار موقت
    users = table("users", column("hashed_password", String()))
    op.execute(users.update().values(hashed_password="temporary_password"))

    # بعد از پر کردن داده‌ها، ستون را NOT NULL کن
    op.alter_column("users", "hashed_password", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
